name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      
      # Genera dinámicamente los environment.ts
      - name: Generate environment.ts
        run: |
          mkdir -p src/environments
          cat > src/environments/environment.ts <<EOF
          export const environment = {
            production: true,
            firebase: {
              apiKey: "${{ secrets.FIREBASE_API_KEY_PROD }}",
              authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN_PROD }}",
              projectId: "${{ secrets.FIREBASE_PROJECT_ID_PROD }}",
              storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET_PROD }}",
              messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID_PROD }}",
              appId: "${{ secrets.FIREBASE_APP_ID_PROD }}"
            }
          };
          EOF
      
      - name: build app
        run: npm run build -- --configuration production
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_APPEARS_DEV }}
          channelId: live
          projectId: appears-dev
